import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "EN" | "RW" | "FR";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "nav.categories": "Categories",
    "nav.deals": "Deals",
    "nav.all_products": "All Products",
    "nav.search_placeholder": "Search products, categories...",
    "nav.momo_accepted": "MTN MoMo accepted",
    "nav.free_delivery": "Free delivery on orders over RWF 50,000",
    "hero.badge": "Rwanda's #1 Online Supermarket",
    "hero.title": "Fresh Groceries, Delivered to Your Door",
    "hero.delivered": "Delivered",
    "hero.subtitle": "Shop 700+ quality products from Kigali's favorite supermarket. Fast delivery, fair prices, and payment with MTN MoMo.",
    "hero.shop_now": "Shop Now",
    "hero.browse": "Browse Categories",
    "hero.trust_delivery": "Free delivery 50K+",
    "hero.trust_sameday": "Same-day delivery",
  "hero.trust_quality": "Quality guaranteed",
  "hero.vip_welcome": "Welcome Back",
  "hero.auth_title_prefix": "Your Favorites,",
  "hero.auth_title_accent": "Refreshed.",
  "hero.auth_subtitle": "We've curated new arrivals and special price drops just for you. Explore what's fresh at Simba today.",
  "hero.quality_freshness": "Quality & Freshness",
    "deals.title": "Fresh Deals Today",
    "deals.hot": "HOT DEALS",
    "deals.view_all": "View all",
    "categories.title": "Shop by Category",
    "categories.subtitle": "Find exactly what you need",
    "categories.all": "All Products",
    "categories.items": "items",
    "footer.tagline": "Rwanda's Online Supermarket",
    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.start_shopping": "Start Shopping",
    "cart.checkout": "Checkout",
    "cart.subtotal": "Subtotal",
    "cart.clear": "Clear cart",
    "trust.title": "TRUSTED BY FAMILIES IN KIGALI",
    "trust.subtitle": "Experience the most reliable grocery shopping in Rwanda with secure payments and guaranteed freshness.",
    "trust.express_delivery": "EXPRESS DELIVERY",
    "trust.express_delivery_desc": "Same-day delivery across Kigali",
    "trust.ssl_secured": "SSL SECURED",
    "trust.ssl_secured_desc": "Your data is 100% protected",
    "trust.easy_returns": "EASY RETURNS",
    "trust.easy_returns_desc": "24h policy for fresh items",
    "trust.secure_pay": "SECURE PAY",
    "trust.secure_pay_desc": "MoMo, Cards & Bank Transfer",
    "trust.live_support": "LIVE SUPPORT",
    "trust.live_support_desc": "24/7 dedicated help desk",
    "trust.premium_quality": "PREMIUM QUALITY",
    "trust.premium_quality_desc": "Hand-picked fresh groceries",
    "unit.per": "per",
    "cat.Alcoholic Drinks": "Alcoholic Drinks",
    "cat.Baby Products": "Baby Products",
    "cat.Cleaning & Sanitary": "Cleaning & Sanitary",
    "cat.Cosmetics & Personal Care": "Cosmetics & Personal Care",
    "cat.Food Products": "Food Products",
    "cat.General": "General",
    "cat.Kitchen Storage": "Kitchen Storage",
    "cat.Kitchenware & Electronics": "Kitchenware & Electronics",
    "cat.Pet Care": "Pet Care",
    "cat.Sports & Wellness": "Sports & Wellness"
  },
  RW: {
    "nav.categories": "Ibyiciro",
    "nav.deals": "Gahunda",
    "nav.all_products": "Ibicuruzwa byose",
    "nav.search_placeholder": "Shaka ibicuruzwa, ibyiciro...",
    "nav.momo_accepted": "MTN MoMo iremewe",
    "nav.free_delivery": "Kugeza ku buntu ku burenganzira burenze RWF 50,000",
    "hero.badge": "Supermarket ya mbere mu Rwanda kuri interineti",
    "hero.title": "Ibiribwa bishya, Bikugezeho mu rugo",
    "hero.delivered": "Bikugezeho",
    "hero.subtitle": "Haha ibicuruzwa 700+ bifite ireme muri supermarket ikunzwe i Kigali. Kugeza vuba, ibiciro byiza, no kwishyura na MTN MoMo.",
    "hero.shop_now": "Haha nonaha",
    "hero.browse": "Reba ibyiciro",
    "hero.trust_delivery": "Kugeza ku buntu 50K+",
    "hero.trust_sameday": "Kugeza uwo munsi",
  "hero.trust_quality": "Ireme ryizewe",
  "hero.vip_welcome": "Murakaza neza",
  "hero.auth_title_prefix": "Ibyo ukunda,",
  "hero.auth_title_accent": "Byavuguruwe.",
  "hero.auth_subtitle": "Twaguteguriye ibicuruzwa bishya n'ibiciro byagabanutse. Reba ibishya muri Simba uyu munsi.",
  "hero.quality_freshness": "Ubuziranenge n'ibishya",
    "deals.title": "Gahunda z'uyu munsi",
    "deals.hot": "Gahunda zishushye",
    "deals.view_all": "Reba byose",
    "categories.title": "Shakira mu byiciro",
    "categories.subtitle": "Bona neza icyo ukeneye",
    "categories.all": "Ibicuruzwa byose",
    "categories.items": "ibicuruzwa",
    "footer.tagline": "Supermarket yo mu Rwanda kuri interineti",
    "cart.title": "Ikarita yawe",
    "cart.empty": "Ikarita yawe irimo ubusa",
    "cart.start_shopping": "Tangira guhaha",
    "cart.checkout": "Ishyura",
    "cart.subtotal": "Igiteranyo",
    "cart.clear": "Vanamo byose",
    "trust.title": "YIZIWE N'IMIRYANGO I KIGALI",
    "trust.subtitle": "Gura ibiribwa byizewe mu Rwanda, wishyure neza kandi ubone ibishya buri munsi.",
    "trust.express_delivery": "KUGEZA VUBA",
    "trust.express_delivery_desc": "Kugeza mu rugo uwo munsi i Kigali",
    "trust.ssl_secured": "UMUTEKANO WIZIWE",
    "trust.ssl_secured_desc": "Imyirondoro yawe irinzwe 100%",
    "trust.easy_returns": "KUGARURA IBINTU",
    "trust.easy_returns_desc": "Kugarura mu masaha 24",
    "trust.secure_pay": "KWISHYURA NEZA",
    "trust.secure_pay_desc": "MoMo, Amakarita & Banki",
    "trust.live_support": "IMFASHANYO MU LIVE",
    "trust.live_support_desc": "Duhari 24/7 ngo tugufashe",
    "trust.premium_quality": "IREME RYO HEJURU",
    "trust.premium_quality_desc": "Ibiribwa byiza batoranyije",
    "unit.per": "kuri",
    "cat.Alcoholic Drinks": "Ibinyobwa bisindisha",
    "cat.Baby Products": "Iby'abana",
    "cat.Cleaning & Sanitary": "Isuku",
    "cat.Cosmetics & Personal Care": "Isura n'Umubiri",
    "cat.Food Products": "Ibiribwa",
    "cat.General": "Ibisanzwe",
    "cat.Kitchen Storage": "Iby'igikoni",
    "cat.Kitchenware & Electronics": "ibikoresho by'igikoni",
    "cat.Pet Care": "Iby'amatungo",
    "cat.Sports & Wellness": "Imyitozo"
  },
  FR: {
    "nav.categories": "Catégories",
    "nav.deals": "Offres",
    "nav.all_products": "Tous les produits",
    "nav.search_placeholder": "Rechercher des produits, catégories...",
    "nav.momo_accepted": "MTN MoMo accepté",
    "nav.free_delivery": "Livraison gratuite dès 50 000 RWF",
    "hero.badge": "Le supermarché en ligne n°1 au Rwanda",
    "hero.title": "Produits frais, livrés à votre porte",
    "hero.delivered": "Livrés",
    "hero.subtitle": "Achetez plus de 700 produits de qualité du supermarché préféré de Kigali. Livraison rapide, prix justes et paiement par MTN MoMo.",
    "hero.shop_now": "Acheter maintenant",
    "hero.browse": "Parcourir les catégories",
    "hero.trust_delivery": "Livraison gratuite 50K+",
    "hero.trust_sameday": "Livraison le jour même",
  "hero.trust_quality": "Qualité garantie",
  "hero.vip_welcome": "Bon retour",
  "hero.auth_title_prefix": "Vos favoris,",
  "hero.auth_title_accent": "rafraîchis.",
  "hero.auth_subtitle": "Nous avons sélectionné de nouveaux arrivages et des baisses de prix pour vous. Découvrez les nouveautés de Simba aujourd'hui.",
  "hero.quality_freshness": "Qualité & fraîcheur",
    "deals.title": "Offres du jour",
    "deals.hot": "OFFRES CHAUDES",
    "deals.view_all": "Voir tout",
    "categories.title": "Acheter par catégorie",
    "categories.subtitle": "Trouvez exactement ce dont vous avez besoin",
    "categories.all": "Tous les produits",
    "categories.items": "articles",
    "footer.tagline": "Le supermarché en ligne du Rwanda",
    "cart.title": "Votre Panier",
    "cart.empty": "Votre panier est vide",
    "cart.start_shopping": "Commencer vos achats",
    "cart.checkout": "Payer",
    "cart.subtotal": "Sous-total",
    "cart.clear": "Vider le panier",
    "trust.title": "APPROUVÉ PAR LES FAMILLES DE KIGALI",
    "trust.subtitle": "Vivez l'expérience de courses la plus fiable au Rwanda avec des paiements sécurisés et une fraîcheur garantie.",
    "trust.express_delivery": "LIVRAISON EXPRESS",
    "trust.express_delivery_desc": "Livraison le jour même à Kigali",
    "trust.ssl_secured": "SSL SÉCURISÉ",
    "trust.ssl_secured_desc": "Vos données sont 100% protégées",
    "trust.easy_returns": "RETOURS FACILES",
    "trust.easy_returns_desc": "Politique de 24h pour les produits frais",
    "trust.secure_pay": "PAIEMENT SÉCURISÉ",
    "trust.secure_pay_desc": "MoMo, Cartes & Transfert bancaire",
    "trust.live_support": "SUPPORT EN DIRECT",
    "trust.live_support_desc": "Assistance dédiée 24/7",
    "trust.premium_quality": "QUALITÉ PREMIUM",
    "trust.premium_quality_desc": "Épicerie fraîche sélectionnée",
    "unit.per": "par",
    "cat.Alcoholic Drinks": "Boissons alcoolisées",
    "cat.Baby Products": "Produits bébé",
    "cat.Cleaning & Sanitary": "Nettoyage & Sanitaire",
    "cat.Cosmetics & Personal Care": "Cosmétiques & Soins",
    "cat.Food Products": "Produits alimentaires",
    "cat.General": "Général",
    "cat.Kitchen Storage": "Rangement Cuisine",
    "cat.Kitchenware & Electronics": "Ustensiles & Électronique",
    "cat.Pet Care": "Soins Animaux",
    "cat.Sports & Wellness": "Sports & Bien-être"
  },
};

Object.assign(translations.EN, {
  "common.default": "Default",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.error": "Error",
  "common.success": "Success",
  "common.not_set": "Not set",
  "common.card": "Card",
  "common.loading": "Loading...",
  "products.no_found": "No products found",
  "products.try_adjustment": "Try a different search or category adjustment",
  "products.load_more": "Load More Products",
  "products.out_of_stock": "Out of Stock",
  "products.notify_me": "Notify Me",
  "products.price_drop": "Price Drop",
  "products.added_cart": "added to cart",
  "products.ai_added_one": "Added {name} to your cart.",
  "products.ai_added_many": "Added {count} products to your cart.",
  "products.ai_no_match_add": "I could not find a product to add yet. Tell me the product name you want.",
  "products.login_favorites": "Please login to save favorites",
  "products.login_alerts": "Please login to get alerts",
  "products.removed_wishlist": "Removed from wishlist",
  "products.added_wishlist": "Added to wishlist",
  "products.wishlist_failed": "Failed to update wishlist",
  "products.alert_success": "We'll notify you when it's back!",
  "products.alert_failed": "Failed to set alert",
  "cart.header_cart": "Your Cart",
  "cart.header_delivery": "Delivery",
  "cart.header_payment": "Payment",
  "cart.header_confirmed": "Confirmed",
  "cart.order_success": "Order Success",
  "pickup.header_branch": "Pickup Branch",
  "pickup.header_deposit": "MoMo Deposit",
  "pickup.order_success": "Pickup Confirmed",
  "pickup.choose_branch": "Choose your pickup branch",
  "pickup.branch_desc": "Your order is sent to this Kigali branch immediately so staff can start preparing it.",
  "pickup.pickup_time": "Pickup Time",
  "pickup.branch": "Branch",
  "pickup.momo_deposit": "MTN MoMo Deposit",
  "pickup.deposit_desc": "Your order requires a 500 RWF deposit to confirm. This demo simulates the MTN MoMo payment flow.",
  "pickup.deposit_due": "Deposit to confirm",
  "pickup.momo_phone": "MTN MoMo phone number",
  "pickup.pick_date": "Pick a date",
  "pickup.time_format_hint": "Choose a date and time. Pickup must be from now until tomorrow 23:59.",
  "pickup.invalid_time_format": "Use pickup time format HH:MM",
  "pickup.invalid_time_past": "Pickup time cannot be in the past",
  "pickup.invalid_time_late": "Pickup time cannot be later than tomorrow 23:59",
  "pickup.deposit": "MoMo Deposit",
  "pickup.choose_pickup": "Choose Pickup",
  "pickup.continue_deposit": "Continue to Deposit",
  "pickup.pay_deposit": "Confirm 500 RWF Deposit",
  "pickup.back_branch": "Go Back to Branch Selection",
  "pickup.branch_ready": "Branch Ready",
  "pickup.order_sent": "Order Sent!",
  "pickup.order_sent_desc": "Your order has been sent to the branch and staff can start preparing it for pickup.",
  "pickup.select_branch_time": "Please select a branch and pickup time",
  "pickup.enter_momo": "Enter your MTN MoMo phone number",
  "cart.items_in_bag": "items in bag",
  "cart.empty_title": "Cart is empty",
  "cart.empty_desc": "Add some fresh groceries to get started!",
  "cart.delivery_address": "Delivery Address",
  "cart.payment_method": "Payment Method",
  "cart.order_placed": "Order Placed!",
  "cart.order_placed_desc": "Success! Your fresh groceries are being packed and will be shipped soon.",
  "cart.back_shopping": "Back to Shopping",
  "cart.total": "Total",
  "cart.processing": "Securely Processing...",
  "cart.checkout_now": "Checkout Now",
  "cart.confirm_address": "Confirm Address",
  "cart.place_order": "Place Order",
  "cart.go_back_cart": "Go Back to Cart",
  "cart.go_back_address": "Go Back to Address Selection",
  "cart.clear_full": "Clear Shopping Cart",
  "cart.cleared": "Cart cleared",
  "cart.login_checkout": "Please login to checkout",
  "cart.add_address_first": "Please add a delivery address in your profile first",
  "cart.add_payment_first": "Please add a payment method in your profile first",
  "cart.select_address_payment": "Please select address and payment method",
  "cart.order_failed": "Failed to place order. Please try again.",
  "profile.personal_info": "Personal Info",
  "profile.my_orders": "My Orders",
  "profile.wishlist": "Wishlist",
  "profile.my_addresses": "My Addresses",
  "profile.help_support": "Help & Support",
  "profile.payments": "Payments",
  "profile.security": "Security",
  "profile.premium_member": "Premium Member",
  "profile.sign_out": "Sign Out",
  "profile.personal_title": "Personal Info",
  "profile.personal_desc": "Update your identity and contact details.",
  "profile.first_name": "First Name",
  "profile.last_name": "Last Name",
  "profile.email": "Email Address",
  "profile.phone": "Phone Number",
  "profile.edit_details": "Edit Profile Details",
  "profile.orders_title": "Order History",
  "profile.orders_desc": "Track your deliveries and manage returns.",
  "profile.no_orders": "No orders placed yet.",
  "order.order": "Order",
  "order.items": "items",
  "order.total": "Total",
  "order.ordered": "Ordered",
  "order.processing": "Processing",
  "order.assigned": "Assigned",
  "order.preparing": "Preparing",
  "order.ready_pickup": "Ready for Pick-up",
  "order.picked_up": "Picked Up",
  "order.shipped": "Shipped",
  "order.delivered": "Delivered",
  "order.cancelled": "Cancelled",
  "order.tracking": "Tracking",
  "order.pickup_branch": "Pickup branch",
  "order.pickup_time": "Pickup time",
  "order.deposit_paid": "MoMo deposit",
  "order.cancel": "Cancel Order",
  "order.return": "Return Items",
  "order.invoice": "Get Invoice",
  "review.title": "Rate your pick-up",
  "review.branch_rating": "Branch rating",
  "review.after_purchase_title": "Rate this branch after your purchase",
  "review.after_purchase_desc": "Your checkout is done. Tell us how this branch feels so other customers can choose better.",
  "review.rate_now": "Rate Branch Now",
  "review.maybe_later": "Maybe Later",
  "review.comment": "How was the branch experience?",
  "review.submit": "Submit Review",
  "review.thanks": "Thanks for reviewing this branch.",
  "review.failed": "Failed to submit review",
  "order.confirm_cancel": "Are you sure you want to cancel this order?",
  "order.cancel_success": "Order cancelled",
  "order.cancel_failed": "Failed to cancel order",
  "order.return_success": "Return request submitted",
  "order.return_failed": "Failed to request return",
  "profile.wishlist_title": "My Wishlist",
  "profile.wishlist_desc": "Products you've saved for later.",
  "profile.wishlist_empty": "Your wishlist is empty.",
  "profile.addresses_desc": "Manage your delivery locations.",
  "profile.add_new": "Add New",
  "profile.add_address": "Add New Address",
  "profile.label": "Label (e.g. Home, Work)",
  "profile.full_name": "Full Name",
  "profile.phone_number": "Phone Number",
  "profile.street": "Street Address",
  "profile.city": "City",
  "profile.district": "District",
  "profile.default_address": "Set as default delivery address",
  "profile.save_address": "Save Address",
  "profile.address_added": "Address Added",
  "profile.address_saved": "Your new address has been saved.",
  "profile.address_deleted": "Address Deleted",
  "profile.payments_title": "Payment Methods",
  "profile.payments_desc": "Securely manage your billing info.",
  "profile.add_method": "Add Method",
  "profile.add_payment": "Add Payment Method",
  "profile.last_four": "Last 4 Digits",
  "profile.expiry": "MM/YY",
  "profile.default_payment": "Set as default payment method",
  "profile.save_method": "Save Method",
  "profile.payment_added": "Payment Method Added",
  "profile.payment_removed": "Payment Method Removed",
  "profile.security_title": "Security Settings",
  "profile.security_desc": "Protect your account and data.",
  "profile.change_password": "Change Password",
  "profile.change_password_desc": "Update your account password regularly.",
  "profile.current_password": "Current Password",
  "profile.new_password": "New Password",
  "profile.confirm_password": "Confirm New Password",
  "profile.update_password": "Update Password",
  "profile.password_changed": "Password Updated",
  "profile.password_changed_desc": "Your password has been changed securely.",
  "profile.password_change_failed": "Password Update Failed",
  "profile.passwords_do_not_match": "The new password and confirmation do not match.",
  "profile.password_required": "Enter your current password, new password, and confirmation.",
  "profile.danger_zone": "Danger Zone",
  "profile.delete_warning": "Deleting your account is permanent and cannot be undone.",
  "profile.delete_account": "Delete Account",
  "support.title": "Help & Support",
  "support.desc": "Find answers or get in touch with our team.",
  "support.faq": "Frequently Asked Questions",
  "support.send_message": "Send us a Message",
  "support.subject": "Subject",
  "support.message_placeholder": "How can we help?",
  "support.submit": "Submit Inquiry",
  "support.sent": "Message Sent",
  "support.sent_desc": "We'll get back to you soon!",
  "support.failed": "Failed to send message.",
  "support.faq.delivery_q": "Where do you deliver?",
  "support.faq.delivery_a": "We deliver all across Kigali, including Kimironko, Nyarutarama, and Kicukiro!",
  "support.faq.hours_q": "What are your delivery hours?",
  "support.faq.hours_a": "We operate from 8 AM to 8 PM daily. Same-day delivery for orders before 2 PM.",
  "support.faq.pay_q": "How can I pay?",
  "support.faq.pay_a": "We accept MTN MoMo, Airtel Money, and all major Credit/Debit cards.",
  "support.chat_title": "Simba Support",
  "support.active_now": "Active Now",
  "support.need_help": "Need Help?",
  "support.ask_placeholder": "Ask about delivery, payment...",
  "support.offline": "I'm sorry, I'm offline at the moment. Please try again later!",
  "support.trouble": "I'm having trouble connecting right now. How else can I help?",
  "notifications.title": "Notifications",
  "notifications.new": "New",
  "notifications.empty": "All caught up!",
  "notifications.clear_all": "Clear All Notifications",
  "recommend.title": "Recommended for You",
  "recommend.desc": "Based on your interests",
  "nav.quick_matches": "Quick Matches",
  "nav.no_products": "No products found",
  "nav.free_delivery_short": "Free Delivery over RWF 50,000",
  "nav.manage_account": "Manage Account",
  "nav.track_orders": "Track Orders",
  "nav.price_drops": "Price drops in Wishlist!",
  "nav.sign_in": "Sign In",
  "nav.sign_out": "Sign Out",
  "nav.user": "User",
  "nav.premium_vip": "Premium VIP",
  "footer.description": "Serving quality and freshness to your doorstep since 2018. Your trusted local supermarket.",
  "footer.rights": "All rights reserved.",
  "catalog.collection": "Our Collection",
  "catalog.results": "Results",
});

Object.assign(translations.RW, {
  "common.default": "Mburabuzi",
  "common.cancel": "Hagarika",
  "common.save": "Bika",
  "common.delete": "Siba",
  "common.error": "Ikosa",
  "common.success": "Byakunze",
  "common.not_set": "Ntabwo byashyizweho",
  "common.card": "Ikarita",
  "common.loading": "Birimo gukora...",
  "products.no_found": "Nta bicuruzwa byabonetse",
  "products.try_adjustment": "Gerageza irindi shakiro cyangwa ikindi cyiciro",
  "products.load_more": "Garagaza ibindi bicuruzwa",
  "products.out_of_stock": "Byarashize",
  "products.notify_me": "Nzabimenyeshe",
  "products.price_drop": "Igiciro cyagabanutse",
  "products.added_cart": "cyashyizwe mu gasanduku",
  "products.ai_added_one": "{name} cyashyizwe mu gasanduku kawe.",
  "products.ai_added_many": "Ibicuruzwa {count} byashyizwe mu gasanduku kawe.",
  "products.ai_no_match_add": "Ntabwo nabonye igicuruzwa cyo gushyiramo. Mbwira izina ry'igicuruzwa ushaka.",
  "products.login_favorites": "Injira kugira ngo ubike ibyo ukunda",
  "products.login_alerts": "Injira kugira ngo ubone imenyesha",
  "products.removed_wishlist": "Cyakuwe ku rutonde rw'ibyo ukunda",
  "products.added_wishlist": "Cyashyizwe ku rutonde rw'ibyo ukunda",
  "products.wishlist_failed": "Kuvugurura urutonde byanze",
  "products.alert_success": "Tuzakumenyesha nikigaruka!",
  "products.alert_failed": "Gushyiraho imenyesha byanze",
  "cart.header_cart": "Agasanduku kawe",
  "cart.header_delivery": "Kugeza",
  "cart.header_payment": "Kwishyura",
  "cart.header_confirmed": "Byemejwe",
  "cart.order_success": "Komande yemejwe",
  "pickup.header_branch": "Ishami ryo gufatiraho",
  "pickup.header_deposit": "Avansi ya MoMo",
  "pickup.order_success": "Gufata byemejwe",
  "pickup.choose_branch": "Hitamo ishami uzafatiraho",
  "pickup.branch_desc": "Komande ihita yoherezwa kuri iri shami rya Kigali kugira ngo abakozi bayitegure.",
  "pickup.pickup_time": "Igihe cyo gufata",
  "pickup.branch": "Ishami",
  "pickup.momo_deposit": "Avansi ya MTN MoMo",
  "pickup.deposit_desc": "Komande yawe isaba avansi ya 500 RWF kugira ngo yemezwe. Iyi demo yigana uburyo bwa MTN MoMo.",
  "pickup.deposit_due": "Avansi yo kwemeza",
  "pickup.momo_phone": "Telefone ya MTN MoMo",
  "pickup.pick_date": "Hitamo itariki",
  "pickup.time_format_hint": "Hitamo itariki n'isaha. Gufata bigomba kuba kuva ubu kugeza ejo saa 23:59.",
  "pickup.invalid_time_format": "Koresha format y'isaha ya HH:MM",
  "pickup.invalid_time_past": "Igihe cyo gufata ntikigomba kuba cyararenze",
  "pickup.invalid_time_late": "Igihe cyo gufata ntigishobora kurenga ejo saa 23:59",
  "pickup.deposit": "Avansi ya MoMo",
  "pickup.choose_pickup": "Hitamo aho ufatira",
  "pickup.continue_deposit": "Komeza kuri avansi",
  "pickup.pay_deposit": "Emeza avansi ya 500 RWF",
  "pickup.back_branch": "Subira guhitamo ishami",
  "pickup.branch_ready": "Ishami ryiteguye",
  "pickup.order_sent": "Komande yoherejwe!",
  "pickup.order_sent_desc": "Komande yawe yoherejwe ku ishami kandi abakozi batangiye kuyitegura.",
  "pickup.select_branch_time": "Hitamo ishami n'igihe cyo gufata",
  "pickup.enter_momo": "Shyiramo telefone ya MTN MoMo",
  "cart.items_in_bag": "ibicuruzwa mu gasanduku",
  "cart.empty_title": "Agasanduku karimo ubusa",
  "cart.empty_desc": "Shyiramo ibiribwa bishya kugira ngo utangire!",
  "cart.delivery_address": "Aderesi yo kugeza",
  "cart.payment_method": "Uburyo bwo kwishyura",
  "cart.order_placed": "Komande yoherejwe!",
  "cart.order_placed_desc": "Byakunze! Ibiribwa byawe birimo gutegurwa kandi bizoherezwa vuba.",
  "cart.back_shopping": "Subira guhaha",
  "cart.total": "Igiteranyo",
  "cart.processing": "Birimo gukorwa mu mutekano...",
  "cart.checkout_now": "Ishyura nonaha",
  "cart.confirm_address": "Emeza aderesi",
  "cart.place_order": "Ohereza komande",
  "cart.go_back_cart": "Subira ku gasanduku",
  "cart.go_back_address": "Subira guhitamo aderesi",
  "cart.clear_full": "Siba ibiri mu gasanduku",
  "cart.cleared": "Agasanduku gasibwe",
  "cart.login_checkout": "Injira kugira ngo wishyure",
  "cart.add_address_first": "Banza wongere aderesi yo kugeza muri profile yawe",
  "cart.add_payment_first": "Banza wongere uburyo bwo kwishyura muri profile yawe",
  "cart.select_address_payment": "Hitamo aderesi n'uburyo bwo kwishyura",
  "cart.order_failed": "Kohereza komande byanze. Ongera ugerageze.",
  "profile.personal_info": "Amakuru bwite",
  "profile.my_orders": "Komande zanjye",
  "profile.wishlist": "Ibyo nkunda",
  "profile.my_addresses": "Aderesi zanjye",
  "profile.help_support": "Ubufasha",
  "profile.payments": "Kwishyura",
  "profile.security": "Umutekano",
  "profile.premium_member": "Umunyamuryango wihariye",
  "profile.sign_out": "Sohoka",
  "profile.personal_title": "Amakuru bwite",
  "profile.personal_desc": "Hindura imyirondoro n'aho baguhamagara.",
  "profile.first_name": "Izina",
  "profile.last_name": "Izina ry'umuryango",
  "profile.email": "Imeyili",
  "profile.phone": "Telefone",
  "profile.edit_details": "Hindura amakuru",
  "profile.orders_title": "Amateka ya komande",
  "profile.orders_desc": "Kurikirana ibicuruzwa no gusaba kugarura.",
  "profile.no_orders": "Nta komande urakora.",
  "order.order": "Komande",
  "order.items": "ibicuruzwa",
  "order.total": "Igiteranyo",
  "order.ordered": "Yatanzwe",
  "order.processing": "Irimo gukorwa",
  "order.assigned": "Yahawe umukozi",
  "order.preparing": "Irategurwa",
  "order.ready_pickup": "Yiteguye gufatwa",
  "order.picked_up": "Yafashwe",
  "order.shipped": "Yoherejwe",
  "order.delivered": "Yageze",
  "order.cancelled": "Yahagaritswe",
  "order.tracking": "Gukurikirana",
  "order.pickup_branch": "Ishami ryo gufatiraho",
  "order.pickup_time": "Igihe cyo gufata",
  "order.deposit_paid": "Avansi ya MoMo",
  "order.cancel": "Hagarika komande",
  "order.return": "Garura ibicuruzwa",
  "order.invoice": "Fata fagitire",
  "review.title": "Tanga amanota ku gufata komande",
  "review.branch_rating": "Amanota y'ishami",
  "review.after_purchase_title": "Tanga amanota kuri iri shami nyuma yo kugura",
  "review.after_purchase_desc": "Warangije kugura. Tubwire uko iri shami rimeze kugira ngo n'abandi bakiriya bahitemo neza.",
  "review.rate_now": "Tanga amanota nonaha",
  "review.maybe_later": "Nyuma gato",
  "review.comment": "Serivisi y'ishami yari imeze ite?",
  "review.submit": "Ohereza isuzuma",
  "review.thanks": "Urakoze gusuzuma iri shami.",
  "review.failed": "Kohereza isuzuma byanze",
  "order.confirm_cancel": "Uremeza ko ushaka guhagarika iyi komande?",
  "order.cancel_success": "Komande yahagaritswe",
  "order.cancel_failed": "Guhagarika komande byanze",
  "order.return_success": "Gusaba kugarura byoherejwe",
  "order.return_failed": "Gusaba kugarura byanze",
  "profile.wishlist_title": "Ibyo nkunda",
  "profile.wishlist_desc": "Ibicuruzwa wabikiye nyuma.",
  "profile.wishlist_empty": "Urutonde rw'ibyo ukunda rurimo ubusa.",
  "profile.addresses_desc": "Genzura aho ibintu bikugeraho.",
  "profile.add_new": "Ongeraho",
  "profile.add_address": "Ongeraho aderesi",
  "profile.label": "Ikirango (Urugo, Akazi)",
  "profile.full_name": "Amazina yose",
  "profile.phone_number": "Numero ya telefone",
  "profile.street": "Aderesi y'umuhanda",
  "profile.city": "Umujyi",
  "profile.district": "Akarere",
  "profile.default_address": "Bikoreshe nk'aderesi mburabuzi",
  "profile.save_address": "Bika aderesi",
  "profile.address_added": "Aderesi yongewemo",
  "profile.address_saved": "Aderesi nshya yabitswe.",
  "profile.address_deleted": "Aderesi yasibwe",
  "profile.payments_title": "Uburyo bwo kwishyura",
  "profile.payments_desc": "Genzura amakuru yo kwishyura mu mutekano.",
  "profile.add_method": "Ongeraho uburyo",
  "profile.add_payment": "Ongeraho uburyo bwo kwishyura",
  "profile.last_four": "Imibare 4 ya nyuma",
  "profile.expiry": "MM/YY",
  "profile.default_payment": "Bikoreshe nk'uburyo mburabuzi bwo kwishyura",
  "profile.save_method": "Bika uburyo",
  "profile.payment_added": "Uburyo bwo kwishyura bwongewemo",
  "profile.payment_removed": "Uburyo bwo kwishyura bwakuweho",
  "profile.security_title": "Igenamiterere ry'umutekano",
  "profile.security_desc": "Rinda konti yawe n'amakuru yawe.",
  "profile.change_password": "Hindura ijambo banga",
  "profile.change_password_desc": "Hindura ijambo banga rya konti kenshi.",
  "profile.current_password": "Ijambo banga ririho",
  "profile.new_password": "Ijambo banga rishya",
  "profile.confirm_password": "Emeza ijambo banga rishya",
  "profile.update_password": "Vugurura ijambo banga",
  "profile.password_changed": "Ijambo banga ryavuguruwe",
  "profile.password_changed_desc": "Ijambo banga ryawe ryahinduwe mu mutekano.",
  "profile.password_change_failed": "Kuvugurura ijambo banga byanze",
  "profile.passwords_do_not_match": "Ijambo banga rishya n'iryemejwe ntibihuye.",
  "profile.password_required": "Shyiramo ijambo banga ririho, irishya n'iryo kwemeza.",
  "profile.danger_zone": "Ahakomeye",
  "profile.delete_warning": "Gusiba konti birahoraho kandi ntibisubirwaho.",
  "profile.delete_account": "Siba konti",
  "support.title": "Ubufasha",
  "support.desc": "Shaka ibisubizo cyangwa utwandikire.",
  "support.faq": "Ibibazo bikunze kubazwa",
  "support.send_message": "Twandikire",
  "support.subject": "Umutwe",
  "support.message_placeholder": "Twagufasha dute?",
  "support.submit": "Ohereza ikibazo",
  "support.sent": "Ubutumwa bwoherejwe",
  "support.sent_desc": "Tuzagusubiza vuba!",
  "support.failed": "Kohereza ubutumwa byanze.",
  "support.faq.delivery_q": "Mugeza hehe?",
  "support.faq.delivery_a": "Tugeza hose i Kigali, harimo Kimironko, Nyarutarama na Kicukiro!",
  "support.faq.hours_q": "Amasaha yo kugeza ni ayahe?",
  "support.faq.hours_a": "Dukora buri munsi kuva saa 8:00 kugeza saa 20:00. Komande zakozwe mbere ya saa 14:00 zigezwa uwo munsi.",
  "support.faq.pay_q": "Nishyura gute?",
  "support.faq.pay_a": "Twemera MTN MoMo, Airtel Money, n'amakarita ya banki.",
  "support.chat_title": "Ubufasha bwa Simba",
  "support.active_now": "Turahari",
  "support.need_help": "Ukeneye ubufasha?",
  "support.ask_placeholder": "Baza ku kugeza, kwishyura...",
  "support.offline": "Mbabarira, ubu ntabwo ndi kuri murandasi. Ongera ugerageze nyuma!",
  "support.trouble": "Hari ikibazo cyo guhuza. Ni iki kindi nagufashamo?",
  "notifications.title": "Amatangazo",
  "notifications.new": "Mashya",
  "notifications.empty": "Nta gishya!",
  "notifications.clear_all": "Siba amatangazo yose",
  "recommend.title": "Ibyagukundira",
  "recommend.desc": "Bishingiye ku byo ukunda",
  "nav.quick_matches": "Ibisubizo bya hafi",
  "nav.no_products": "Nta bicuruzwa byabonetse",
  "nav.free_delivery_short": "Kugeza ku buntu kuri RWF 50,000+",
  "nav.manage_account": "Genzura konti",
  "nav.track_orders": "Kurikirana komande",
  "nav.price_drops": "Ibiciro byagabanutse mu byo ukunda!",
  "nav.sign_in": "Injira",
  "nav.sign_out": "Sohoka",
  "nav.user": "Umukiriya",
  "nav.premium_vip": "VIP",
  "footer.description": "Tukugezaho ubuziranenge n'ibishya kuva 2018. Supermarket yawe yizewe.",
  "footer.rights": "Uburenganzira bwose burabitswe.",
  "catalog.collection": "Ibicuruzwa byacu",
  "catalog.results": "Ibisubizo",
});

Object.assign(translations.FR, {
  "common.default": "Par défaut",
  "common.cancel": "Annuler",
  "common.save": "Enregistrer",
  "common.delete": "Supprimer",
  "common.error": "Erreur",
  "common.success": "Succès",
  "common.not_set": "Non défini",
  "common.card": "Carte",
  "common.loading": "Chargement...",
  "products.no_found": "Aucun produit trouvé",
  "products.try_adjustment": "Essayez une autre recherche ou catégorie",
  "products.load_more": "Charger plus de produits",
  "products.out_of_stock": "Rupture de stock",
  "products.notify_me": "Me prévenir",
  "products.price_drop": "Baisse de prix",
  "products.added_cart": "ajouté au panier",
  "products.ai_added_one": "{name} ajouté au panier.",
  "products.ai_added_many": "{count} produits ajoutés au panier.",
  "products.ai_no_match_add": "Je n'ai pas encore trouvé de produit à ajouter. Indiquez le nom du produit souhaité.",
  "products.login_favorites": "Connectez-vous pour enregistrer vos favoris",
  "products.login_alerts": "Connectez-vous pour recevoir des alertes",
  "products.removed_wishlist": "Retiré de la liste d'envies",
  "products.added_wishlist": "Ajouté à la liste d'envies",
  "products.wishlist_failed": "Échec de la mise à jour de la liste",
  "products.alert_success": "Nous vous préviendrons quand il sera de retour !",
  "products.alert_failed": "Échec de l'alerte",
  "cart.header_cart": "Votre panier",
  "cart.header_delivery": "Livraison",
  "cart.header_payment": "Paiement",
  "cart.header_confirmed": "Confirmé",
  "cart.order_success": "Commande réussie",
  "pickup.header_branch": "Agence de retrait",
  "pickup.header_deposit": "Acompte MoMo",
  "pickup.order_success": "Retrait confirmé",
  "pickup.choose_branch": "Choisissez votre agence de retrait",
  "pickup.branch_desc": "Votre commande est envoyée immédiatement à cette agence de Kigali pour préparation.",
  "pickup.pickup_time": "Heure de retrait",
  "pickup.branch": "Agence",
  "pickup.momo_deposit": "Acompte MTN MoMo",
  "pickup.deposit_desc": "Votre commande nécessite un acompte de 500 RWF pour être confirmée. Cette démo simule le paiement MTN MoMo.",
  "pickup.deposit_due": "Acompte de confirmation",
  "pickup.momo_phone": "Numéro MTN MoMo",
  "pickup.pick_date": "Choisir une date",
  "pickup.time_format_hint": "Choisissez une date et une heure. Le retrait doit être entre maintenant et demain 23:59.",
  "pickup.invalid_time_format": "Utilisez le format d'heure HH:MM",
  "pickup.invalid_time_past": "L'heure de retrait ne peut pas être dans le passé",
  "pickup.invalid_time_late": "L'heure de retrait ne peut pas être après demain 23:59",
  "pickup.deposit": "Acompte MoMo",
  "pickup.choose_pickup": "Choisir le retrait",
  "pickup.continue_deposit": "Continuer vers l'acompte",
  "pickup.pay_deposit": "Confirmer l'acompte de 500 RWF",
  "pickup.back_branch": "Retour au choix de l'agence",
  "pickup.branch_ready": "Agence prête",
  "pickup.order_sent": "Commande envoyée !",
  "pickup.order_sent_desc": "Votre commande a été envoyée à l'agence et le personnel peut commencer la préparation.",
  "pickup.select_branch_time": "Sélectionnez une agence et une heure de retrait",
  "pickup.enter_momo": "Entrez votre numéro MTN MoMo",
  "cart.items_in_bag": "articles dans le panier",
  "cart.empty_title": "Le panier est vide",
  "cart.empty_desc": "Ajoutez des produits frais pour commencer !",
  "cart.delivery_address": "Adresse de livraison",
  "cart.payment_method": "Méthode de paiement",
  "cart.order_placed": "Commande passée !",
  "cart.order_placed_desc": "Succès ! Vos courses sont en préparation et seront bientôt expédiées.",
  "cart.back_shopping": "Retour aux achats",
  "cart.total": "Total",
  "cart.processing": "Traitement sécurisé...",
  "cart.checkout_now": "Passer au paiement",
  "cart.confirm_address": "Confirmer l'adresse",
  "cart.place_order": "Passer la commande",
  "cart.go_back_cart": "Retour au panier",
  "cart.go_back_address": "Retour au choix de l'adresse",
  "cart.clear_full": "Vider le panier",
  "cart.cleared": "Panier vidé",
  "cart.login_checkout": "Connectez-vous pour payer",
  "cart.add_address_first": "Ajoutez d'abord une adresse de livraison dans votre profil",
  "cart.add_payment_first": "Ajoutez d'abord une méthode de paiement dans votre profil",
  "cart.select_address_payment": "Sélectionnez une adresse et une méthode de paiement",
  "cart.order_failed": "Échec de la commande. Veuillez réessayer.",
  "profile.personal_info": "Infos personnelles",
  "profile.my_orders": "Mes commandes",
  "profile.wishlist": "Liste d'envies",
  "profile.my_addresses": "Mes adresses",
  "profile.help_support": "Aide & support",
  "profile.payments": "Paiements",
  "profile.security": "Sécurité",
  "profile.premium_member": "Membre Premium",
  "profile.sign_out": "Se déconnecter",
  "profile.personal_title": "Infos personnelles",
  "profile.personal_desc": "Mettez à jour votre identité et vos coordonnées.",
  "profile.first_name": "Prénom",
  "profile.last_name": "Nom",
  "profile.email": "Adresse e-mail",
  "profile.phone": "Téléphone",
  "profile.edit_details": "Modifier les détails",
  "profile.orders_title": "Historique des commandes",
  "profile.orders_desc": "Suivez vos livraisons et gérez les retours.",
  "profile.no_orders": "Aucune commande pour le moment.",
  "order.order": "Commande",
  "order.items": "articles",
  "order.total": "Total",
  "order.ordered": "Commandé",
  "order.processing": "En traitement",
  "order.assigned": "Assignée",
  "order.preparing": "En préparation",
  "order.ready_pickup": "Prête au retrait",
  "order.picked_up": "Retirée",
  "order.shipped": "Expédié",
  "order.delivered": "Livré",
  "order.cancelled": "Annulé",
  "order.tracking": "Suivi",
  "order.pickup_branch": "Agence de retrait",
  "order.pickup_time": "Heure de retrait",
  "order.deposit_paid": "Acompte MoMo",
  "order.cancel": "Annuler la commande",
  "order.return": "Retourner les articles",
  "order.invoice": "Obtenir la facture",
  "review.title": "Notez votre retrait",
  "review.branch_rating": "Note de l'agence",
  "review.after_purchase_title": "Notez cette agence après votre achat",
  "review.after_purchase_desc": "Votre achat est terminé. Dites-nous comment vous trouvez cette agence pour aider les autres clients.",
  "review.rate_now": "Noter l'agence",
  "review.maybe_later": "Plus tard",
  "review.comment": "Comment était l'expérience en agence ?",
  "review.submit": "Envoyer l'avis",
  "review.thanks": "Merci pour votre avis sur cette agence.",
  "review.failed": "Échec de l'envoi de l'avis",
  "order.confirm_cancel": "Voulez-vous vraiment annuler cette commande ?",
  "order.cancel_success": "Commande annulée",
  "order.cancel_failed": "Échec de l'annulation",
  "order.return_success": "Demande de retour envoyée",
  "order.return_failed": "Échec de la demande de retour",
  "profile.wishlist_title": "Ma liste d'envies",
  "profile.wishlist_desc": "Produits enregistrés pour plus tard.",
  "profile.wishlist_empty": "Votre liste d'envies est vide.",
  "profile.addresses_desc": "Gérez vos lieux de livraison.",
  "profile.add_new": "Ajouter",
  "profile.add_address": "Ajouter une adresse",
  "profile.label": "Libellé (ex. Maison, Travail)",
  "profile.full_name": "Nom complet",
  "profile.phone_number": "Numéro de téléphone",
  "profile.street": "Adresse",
  "profile.city": "Ville",
  "profile.district": "District",
  "profile.default_address": "Définir comme adresse de livraison par défaut",
  "profile.save_address": "Enregistrer l'adresse",
  "profile.address_added": "Adresse ajoutée",
  "profile.address_saved": "Votre nouvelle adresse a été enregistrée.",
  "profile.address_deleted": "Adresse supprimée",
  "profile.payments_title": "Méthodes de paiement",
  "profile.payments_desc": "Gérez vos informations de facturation en sécurité.",
  "profile.add_method": "Ajouter",
  "profile.add_payment": "Ajouter une méthode de paiement",
  "profile.last_four": "4 derniers chiffres",
  "profile.expiry": "MM/AA",
  "profile.default_payment": "Définir comme méthode de paiement par défaut",
  "profile.save_method": "Enregistrer",
  "profile.payment_added": "Méthode de paiement ajoutée",
  "profile.payment_removed": "Méthode de paiement supprimée",
  "profile.security_title": "Paramètres de sécurité",
  "profile.security_desc": "Protégez votre compte et vos données.",
  "profile.change_password": "Changer le mot de passe",
  "profile.change_password_desc": "Mettez régulièrement à jour le mot de passe.",
  "profile.current_password": "Mot de passe actuel",
  "profile.new_password": "Nouveau mot de passe",
  "profile.confirm_password": "Confirmer le nouveau mot de passe",
  "profile.update_password": "Mettre à jour le mot de passe",
  "profile.password_changed": "Mot de passe mis à jour",
  "profile.password_changed_desc": "Votre mot de passe a été modifié en toute sécurité.",
  "profile.password_change_failed": "Échec de la mise à jour du mot de passe",
  "profile.passwords_do_not_match": "Le nouveau mot de passe et la confirmation ne correspondent pas.",
  "profile.password_required": "Saisissez le mot de passe actuel, le nouveau mot de passe et la confirmation.",
  "profile.danger_zone": "Zone dangereuse",
  "profile.delete_warning": "La suppression du compte est permanente et irréversible.",
  "profile.delete_account": "Supprimer le compte",
  "support.title": "Aide & support",
  "support.desc": "Trouvez des réponses ou contactez notre équipe.",
  "support.faq": "Questions fréquentes",
  "support.send_message": "Envoyez-nous un message",
  "support.subject": "Sujet",
  "support.message_placeholder": "Comment pouvons-nous aider ?",
  "support.submit": "Envoyer la demande",
  "support.sent": "Message envoyé",
  "support.sent_desc": "Nous vous répondrons bientôt !",
  "support.failed": "Échec de l'envoi du message.",
  "support.faq.delivery_q": "Où livrez-vous ?",
  "support.faq.delivery_a": "Nous livrons partout à Kigali, y compris Kimironko, Nyarutarama et Kicukiro !",
  "support.faq.hours_q": "Quels sont vos horaires de livraison ?",
  "support.faq.hours_a": "Nous opérons tous les jours de 8h à 20h. Livraison le jour même pour les commandes avant 14h.",
  "support.faq.pay_q": "Comment puis-je payer ?",
  "support.faq.pay_a": "Nous acceptons MTN MoMo, Airtel Money et les principales cartes bancaires.",
  "support.chat_title": "Support Simba",
  "support.active_now": "Actif maintenant",
  "support.need_help": "Besoin d'aide ?",
  "support.ask_placeholder": "Demandez livraison, paiement...",
  "support.offline": "Désolé, je suis hors ligne pour le moment. Réessayez plus tard !",
  "support.trouble": "J'ai du mal à me connecter. Comment puis-je aider autrement ?",
  "notifications.title": "Notifications",
  "notifications.new": "Nouveau",
  "notifications.empty": "Tout est à jour !",
  "notifications.clear_all": "Effacer toutes les notifications",
  "recommend.title": "Recommandé pour vous",
  "recommend.desc": "Selon vos intérêts",
  "nav.quick_matches": "Résultats rapides",
  "nav.no_products": "Aucun produit trouvé",
  "nav.free_delivery_short": "Livraison gratuite dès 50 000 RWF",
  "nav.manage_account": "Gérer le compte",
  "nav.track_orders": "Suivre les commandes",
  "nav.price_drops": "Baisses de prix dans la liste !",
  "nav.sign_in": "Se connecter",
  "nav.sign_out": "Se déconnecter",
  "nav.user": "Utilisateur",
  "nav.premium_vip": "Premium VIP",
  "footer.description": "Qualité et fraîcheur à votre porte depuis 2018. Votre supermarché local de confiance.",
  "footer.rights": "Tous droits réservés.",
  "catalog.collection": "Notre collection",
  "catalog.results": "Résultats",
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("simba-language");
    return saved === "RW" || saved === "FR" || saved === "EN" ? saved : "EN";
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("simba-language", lang);
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
